In [1]:
# Let's start data wrangling on data_online_retail dataset.

In [2]:
# As the first step, I import Python libraries.

import numpy as np
import pandas as pd
import datetime as dt
import os

In [3]:
# The data source for this project is an Excel file.

retail_df = pd.read_csv('/content/data_online_retail.csv', encoding='latin1')

In [4]:
retail_df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [5]:
retail_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87742 entries, 0 to 87741
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    87742 non-null  object
 1   StockCode    87742 non-null  object
 2   Description  87462 non-null  object
 3   Quantity     87742 non-null  int64
 4   InvoiceDate  87742 non-null  object
 5   UnitPrice    87742 non-null  float64
 6   CustomerID   55910 non-null  float64
 7   Country      87742 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 5.4+ MB

In [6]:
retail_df.describe()

           Quantity     UnitPrice    CustomerID
count  87742.000000  87742.000000  55910.000000
mean       8.538761      5.434216  15351.550367
std      358.726762    126.219074   1770.622167
min   -74215.000000      0.000000  12346.000000
25%        1.000000      1.250000  13871.000000
50%        3.000000      2.510000  15311.000000
75%        8.000000      4.250000  17001.000000
max    74215.000000  16888.020000  18283.000000

In [7]:
retail_df.describe().T

,count,mean,std,min,25%,50%,75%,max
Quantity,87742.0,8.538761,358.726762,-74215.0,1.00,3.00,8.00,74215.00
UnitPrice,87742.0,5.434216,126.219074,0.0,1.25,2.51,4.25,16888.02
CustomerID,55910.0,15351.550367,1770.622167,12346.0,13871.00,15311.00,17001.00,18283.00

In [8]:
retail_df.shape

(87742, 8)

In [9]:
retail_df.isnull().sum()

InvoiceNo          0
StockCode          0
Description      280
Quantity           0
InvoiceDate        0
UnitPrice          0
CustomerID     31832
Country            0
dtype: int64

In [10]:
# Let's drop Null values from customer_id and Description, since both of those are small portions of dataframe.

retail_df = retail_df.dropna(subset=['CustomerID'])
retail_df = retail_df.dropna(subset=['Description'])

In [11]:
retail_df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [12]:
retail_df.shape

(55910, 8)

In [13]:
# Let's chaeck data types:

retail_df.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

In [14]:
# These data types need to be changed:

# InvoiceDate >>> from string to datetime
# InvoiceNo >>> from string to float64
# Quantity >>> from float to integer

# However, InvoiceNo cannot be converted to float because it includes alphabet letters. So we keep it as string.

retail_df['InvoiceDate'] = pd.to_datetime(retail_df['InvoiceDate'])

retail_df['Quantity'] = retail_df['Quantity'].astype('int64')

In [15]:
retail_df.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

In [16]:
# Everything else looks good to me.
# We do not have any Null values.
# All data types are correct.
# All columns have appropriate name.

In [17]:
# Let's print head and tail of retail_df and see if we can find something to explore.

retail_df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [18]:
retail_df.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
87644,543688,22828,REGENCY MIRROR WITH SHUTTERS,2,2011-02-11 11:36:00,145.00,15270.0,United Kingdom
87645,543691,35004B,SET OF 3 BLACK FLYING DUCKS,48,2011-02-11 11:38:00,4.65,17924.0,United Kingdom
87646,543693,22469,HEART OF WICKER SMALL,40,2011-02-11 11:40:00,1.45,12897.0,United Kingdom
87647,543693,22470,HEART OF WICKER LARGE,24,2011-02-11 11:40:00,2.95,12897.0,United Kingdom
87648,C543706,22423,REGENCY CAKESTAND 3 TIER,-1,2011-02-11 11:44:00,12.75,15044.0,United Kingdom

In [19]:
# Lets' find max and min price:

print(f"Cheapest item is {retail_df['UnitPrice'].min()}")

print(f"Most expensive item is {retail_df['UnitPrice'].max()}")

Cheapest item is 0.0
Most expensive item is 1715.85

In [20]:
# The cheapest item is 0$ which means the data was not captured. I keep those rows since we still can extract useful information.

In [21]:
# Let's find mosgt ordered and least ordered items:

print(f"Most ordered item is {retail_df['Quantity'].max()}")
print(f"Least ordered item is {retail_df['Quantity'].min()}")

Most ordered item is 74215
Least ordered item is -74215

In [22]:
# Weird! We have negative quantity. Let's explore the Quantity:

retail_df['Quantity'].unique()

array([     6,      8,      2,     32,      3,      4,     24,     12,
           48,     18,     20,     36,     80,     64,     10,    120,
           96,     23,      5,      1,     -1,     50,     40,    100,
          192,    432,    144,    288,    -12,    -24,     16,      9,
          128,     25,     30,     28,      7,     72,    200,    600,
          480,     -6,     14,     -2,     -4,     -5,     -7,     -3,
           11,     70,    252,     60,    216,    384,     27,    108,
           52,  -9360,     75,    270,     42,    240,     90,    320,
           17,   1824,    204,     69,    -36,   -192,   -144,    160,
         2880,   1400,     19,     39,    -48,    -50,     56,     13,
         1440,     -8,     15,    720,    -20,    156,    324,     41,
          -10,    -72,    -11,    402,    378,    150,    300,     22,
           34,    408,    972,    208,   1008,     26,   1000,    -25,
         1488,    250,   1394,    400,    110,    -14,     37,    -33,
           78,     -9,     21,    272,     84,    -47,    -18,    -96,
           47,    -15,    -30,   1728,     38,    -60,    -16,     53,
         -240,     76,    576,    -32,     29,   2400,    500,    -80,
          180,   -300,   -500,    -23,    -13,    960,    -21,   1296,
         -150,    -17,    147,    168,    256,    -40,   -100,     54,
           31,    860,   1010,   1356,   1284,    186,    114,    360,
         1930,   2000,   3114,   1300,    670,    176,    648,     62,
        74215, -74215,     89,     33,     46,   -120,    112,    456,
          900,   -600,    -42,    -94,     45,    130,   2592,    420,
          800,     35,   1200,    864,    504,    -76,   -200])

In [23]:
# Negative quantity is misleading. Let's change them to zero.

retail_df['Quantity'] = retail_df['Quantity'].where(retail_df['Quantity'] >= 0, 0)

retail_df['Quantity'].unique()

array([    6,     8,     2,    32,     3,     4,    24,    12,    48,
          18,    20,    36,    80,    64,    10,   120,    96,    23,
           5,     1,     0,    50,    40,   100,   192,   432,   144,
         288,    16,     9,   128,    25,    30,    28,     7,    72,
         200,   600,   480,    14,    11,    70,   252,    60,   216,
         384,    27,   108,    52,    75,   270,    42,   240,    90,
         320,    17,  1824,   204,    69,   160,  2880,  1400,    19,
          39,    56,    13,  1440,    15,   720,   156,   324,    41,
         402,   378,   150,   300,    22,    34,   408,   972,   208,
        1008,    26,  1000,  1488,   250,  1394,   400,   110,    37,
          78,    21,   272,    84,    47,  1728,    38,    53,    76,
         576,    29,  2400,   500,   180,   960,  1296,   147,   168,
         256,    54,    31,   860,  1010,  1356,  1284,   186,   114,
         360,  1930,  2000,  3114,  1300,   670,   176,   648,    62,
       74215,    89,    33,    46,   112,   456,   900,    45,   130,
        2592,   420,   800,    35,  1200,   864,   504])

In [24]:
# As the last step, let's see which customer purchased more items:

retail_df['CustomerID'].value_counts()

CustomerID
12748.0    695
15311.0    620
14606.0    594
17841.0    591
14911.0    525
          ...
16593.0      1
13953.0      1
13029.0      1
15885.0      1
13747.0      1
Name: count, Length: 1516, dtype: int64

In [25]:
# I would like to use describe() method again to see if I can find outliers at this stage:

retail_df.describe().T

,count,mean,min,25%,50%,75%,max,std
Quantity,55910.0,13.49315,0.0,2.0,4.0,12.0,74215.0,317.388938
InvoiceDate,55910,2011-01-01 14:12:30.859595776,2010-12-01 08:26:00,2010-12-09 14:08:00,2011-01-05 12:02:00,2011-01-24 09:52:00,2011-02-11 11:44:00,NaN
UnitPrice,55910.0,3.281204,0.0,1.25,1.95,3.75,1715.85,10.546353
CustomerID,55910.0,15351.550367,12346.0,13871.0,15311.0,17001.0,18283.0,1770.622167

In [26]:
# Max number of Quantity is 74215, which means a customer has that many order. Let's dive deeper on this:

retail_df['Quantity'].sort_values(ascending=False).head(10)

61619    74215
52711     3114
4945      2880
80742     2592
87631     2400
32671     2400
52710     2000
52709     1930
4850      1824
25920     1728
Name: Quantity, dtype: int64

In [27]:
# Yes! I just found an outlier. I am going to remove Quantity of 74215 since that looks a wrong captured data.
# This value definitely affect std of Quantity attribute.

retail_df = retail_df[retail_df['Quantity'] != 74215]

In [28]:
# Let's do the exact same process to see if we find any outliers in UnitPrice column:

retail_df['UnitPrice'].sort_values(ascending=False).head(10)

73446    1715.85
45622    1126.00
4989      295.00
32484     295.00
87141     295.00
51636     295.00
82768     295.00
36165     295.00
14498     281.00
19392     267.12
Name: UnitPrice, dtype: float64

In [29]:
# And also sort prices from low to high:

retail_df['UnitPrice'].sort_values().head(10)

56674    0.00
40089    0.00
86789    0.00
33576    0.00
47070    0.00
9302     0.00
47068    0.00
4287     0.03
14788    0.07
219      0.10
Name: UnitPrice, dtype: float64

In [30]:
# We cannopt rely on UnitPrice average, because we have so many values close to zero which looks not correct.
# I do not remove these values, but I make sure to not involve average price value in my analysis.

# There are also two UnitPrice values which are much higher than others.
# Hard to say if those are bad data becasue an online store may have expensive items as well.
# Howeve, if those super expensive items are ordered only one time, we can remove them since they do not easily go under any segment.

In [31]:
retail_df['UnitPrice'][retail_df['UnitPrice'] > 500].count()

np.int64(2)

In [32]:
# Only two ordered items are that much expensive.
# I remove those two values because this online retail should not sell items with those prices.

retail_df = retail_df[retail_df['UnitPrice'] <= 500]

In [33]:
# We should see some change in mean value if I call describe() again:

retail_df.describe().T

,count,mean,min,25%,50%,75%,max,std
Quantity,55907.0,12.166401,0.0,2.0,4.0,12.0,3114.0,47.487581
InvoiceDate,55907,2011-01-01 14:11:17.233620224,2010-12-01 08:26:00,2010-12-09 14:08:00,2011-01-05 12:02:00,2011-01-24 09:52:00,2011-02-11 11:44:00,NaN
UnitPrice,55907.0,3.23053,0.0,1.25,1.95,3.75,295.0,6.01839
CustomerID,55907.0,15351.705386,12346.0,13871.0,15311.0,17001.0,18283.0,1770.543095

In [34]:
# We are done with data cleaning. The data looks clean now.
# Let's save the result to new Excel file and keep it for future work.

retail_df.to_csv('cleansed_online_retail.csv', index=False)